import spellCheck

print("OCR Result: \HER'rA HAEHNCHENBR.")
print(spellCheck.main("\HER'rA HAEHNCHENBR.", "product"))
print("")
print("OCR Result: \MILKA TAFELSCHUKO.")
print(spellCheck.main("\MILKA TAFELSCHUKO.", "product"))
print("")
print("OCR Result: \WC ENTE CITRUS-GEL")
print(spellCheck.main("\WC ENTE CITRUS-GEL", "product"))
print("")
print("OCR Result: E&G SCHLAGSAHNE")
print(spellCheck.main("E&G SCHLAGSAHNE", "product"))
print("")
print("OCR Result: WILT.SALAMI LIGHT")
print(spellCheck.main("WILT.SALAMI LIGHT", "product"))
print("")
print("OCR Result: \ E .RASPELSCHOKOLADE")
print(spellCheck.main("\ E .RASPELSCHOKOLADE", "product"))
print("")
print("OCR Result: \MILKA TAFELSCHOKO.")
print(spellCheck.main("\MILKA TAFELSCHOKO.", "product"))
print("")
print("OCR Result: \MILKA TAFELSCHUKQ.")
print(spellCheck.main("\MILKA TAFELSCHUKQ.", "product"))
print("")
print("OCR Result: B&G SCHLAGSAHNE")
print(spellCheck.main("B&G SCHLAGSAHNE", "product"))
print("")
print("OCR Result: RUF VANILZUCKER")
print(spellCheck.main("RUF VANILZUCKER", "product"))
print("")
print("OCR Result: G&G MEHRKORNBROT")
print(spellCheck.main("G&G MEHRKORNBROT", "product"))
print("")
print("OCR Result: G&G KU NROLLE")
print(spellCheck.main("G&G KU NROLLE", "product"))


